inherit_from: .rubocop_todo.yml

# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Offense count: 144
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs, NumberOfEmptyLines.
Layout/EmptyLineBetweenDefs:
  Exclude:
    - 'lib/watir/elements/html_elements.rb'
    - 'lib/watir/elements/svg_elements.rb'

# Offense count: 2
# Cop supports --auto-correct.
Layout/EmptyLines:
  Exclude:
    - 'lib/watir/elements/html_elements.rb'
    - 'lib/watir/elements/svg_elements.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines
Layout/EmptyLinesAroundModuleBody:
  Exclude:
    - 'lib/watir/elements/html_elements.rb'
    - 'lib/watir/elements/svg_elements.rb'

# Offense count: 85
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Offense count: 2
Lint/DuplicateMethods:
  Exclude:
    - 'lib/watirspec.rb'

# Offense count: 1
Lint/HandleExceptions:
  Exclude:
    - 'lib/watirspec.rb'

# Offense count: 28
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/watir/locators/element/selector_builder.rb'
    - 'lib/watir/generator/base/generator.rb'
