rvm:
  - 2.0
  - 2.1
  - 2.2
notifications:
  recipients:
    - p0deje@gmail.com
    - jarmo.p@gmail.com
    - titusfortner@gmail.com
  irc: "irc.freenode.net#watir"
sudo: true
before_script:
  - support/travis.sh
script: bundle exec rake $RAKE_TASK
env:
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=43 CHROMEDRIVER=2.18
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=42 CHROMEDRIVER=2.18
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=41 CHROMEDRIVER=2.18
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=43 CHROMEDRIVER=2.17
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=44 CHROMEDRIVER=2.17
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=41 CHROMEDRIVER=2.17
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=43 CHROMEDRIVER=2.16
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=42 CHROMEDRIVER=2.16
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=41 CHROMEDRIVER=2.16
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=43 CHROMEDRIVER=2.15
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=42 CHROMEDRIVER=2.15
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome BROWSER_VERSION=41 CHROMEDRIVER=2.15
  - RAKE_TASK=yard:doctest
