rvm:
  - 2.0
  - 2.1
  - 2.2
notifications:
  recipients:
    - p0deje@gmail.com
    - jarmo.p@gmail.com
    - titusfortner@gmail.com
  irc: "irc.freenode.net#watir"
sudo: true
before_script:
  - support/travis.sh
script: bundle exec rake $RAKE_TASK
env:
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=firefox
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=firefox ALWAYS_LOCATE=false
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=firefox PREFER_CSS=1 SELECTOR_STATS=1
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome ALWAYS_LOCATE=false
  - RAKE_TASK=spec WATIR_WEBDRIVER_BROWSER=chrome PREFER_CSS=1 SELECTOR_STATS=1
  - RAKE_TASK=yard:doctest
