# Please note that we should not be using container-based infrastructure
# because Chrome requires a lot of shared memory and Travis does not allow
# use host's /dev/shm.
sudo: required
dist: trusty
cache: bundler
notifications:
  recipients:
    - titusfortner@gmail.com
before_script:
  - support/travis.sh
script: bundle exec rake $RAKE_TASK

_version:
  two: &two
    language: ruby
    rvm: 2.2.7
  three: &three
    language: ruby
    rvm: 2.3.4
  four: &four
    language: ruby
    rvm: 2.4.1

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-legacy: &firefox-legacy
    addons:
      firefox: "45.9"
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
     addons:
       chrome: stable

matrix:
  include:
      - env: RAKE_TASK=spec:firefox
        <<: *two
        <<: *firefox
      - env: RAKE_TASK=spec:firefox
        <<: *three
        <<: *firefox
      - env: RAKE_TASK=spec:firefox
        <<: *four
        <<: *firefox
